kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: node-drainer-user-cluster-role-binding
subjects:
  - kind: User
    name: lambda
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: node-drainer-cluster-access
  apiGroup: rbac.authorization.k8s.io
