kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: node-drainer-cluster-access
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/eviction", "nodes"]
    verbs: ["create", "list", "patch"]
